name: Compilar APK de Cordova

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Configurar Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configurar Android SDK
      uses: android-actions/setup-android@v3

    - name: Instalar Cordova
      run: npm install -g cordova

    - name: Crear Estructura Temporal de Cordova
      run: |
        mkdir cordova_build
        mv css img js index.html config.xml cordova_build/
        cd cordova_build
        mkdir www
        mv css img js index.html www/
        cordova platform add android --nosave
        cordova build android --device
        mv platforms/android/app/build/outputs/apk/debug/app-debug.apk ../app-debug.apk

    - name: Guardar el archivo APK listo
      uses: actions/upload-artifact@v4
      with:
        name: mi-app-apk
        path: app-debug.apk
